const employees = [{
    id: 1,
    first_name: "Lois",
    last_name: "Boeck",
    email: "lboeck0@squidoo.com",
    gender: "Female",
    country: "Bahrain",
    department: "Human Resources",
    salary: 85000,
}, 
{
    id: 2,
    first_name: "Brunhilde",
    last_name: "Overlow",
    email: "boverlow1@trellian.com",
    gender: "Female",
    country: "China",
    department: "Research and Development",
    salary: 255000,
}, 
{
    id: 3,
    first_name: "Fernanda",
    last_name: "Hatton",
    email: "fhatton2@vk.com",
    gender: "Female",
    country: "Philippines",
    department: "Legal",
    salary: 155000,
}, 
{
    id: 4,
    first_name: "Genevieve",
    last_name: "Aberkirder",
    email: "gaberkirder3@toplist.cz",
    gender: "Female",
    country: "Indonesia",
    department: "Product Management",
    salary: 110000,
}, 
{
    id: 5,
    first_name: "Patsy",
    last_name: "Baradel",
    email: "pbaradel4@independent.co.uk",
    gender: "Male",
    country: "Haiti",
    department: "Human Resources",
    salary: 110000,
}, 
{
    id: 6,
    first_name: "Sergent",
    last_name: "Yetton",
    email: "syetton5@issuu.com",
    gender: "Male",
    country: "Indonesia",
    department: "Accounting",
    salary: 140000,
}, 
{
    id: 7,
    first_name: "Kalvin",
    last_name: "Manneville",
    email: "kmanneville6@t-online.de",
    gender: "Male",
    country: "Netherlands",
    department: "Product Management",
    salary: 290000,
}, 
{
    id: 8,
    first_name: "Danica",
    last_name: "Tootin",
    email: "dtootin7@twitter.com",
    gender: "Female",
    country: "Yemen",
    department: "Services",
    salary: 120000,
},
{
    id: 9,
    first_name: "Paolo",
    last_name: "Palin",
    email: "ppalin8@bigcartel.com",
    gender: "Male",
    country: "Ukraine",
    department: "Engineering",
    salary: 275000,
},
{
    id: 10,
    first_name: "Arlen",
    last_name: "Helks",
    email: "ahelks9@t.co",
    gender: "Male",
    country: "Belarus",
    department: "Research and Development",
    salary: 220000,
},
{
    id: 11,
    first_name: "Marcellus",
    last_name: "Antrobus",
    email: "mantrobusa@flavors.me",
    gender: "Male",
    country: "Poland",
    department: "Support",
    salary: 250000,
},
{
    id: 12,
    first_name: "Cory",
    last_name: "Clementson",
    email: "cclementsonb@netvibes.com",
    gender: "Male",
    country: "Dominican Republic",
    department: "Marketing",
    salary: 110000,
},
{
    id: 13,
    first_name: "Sibilla",
    last_name: "Viggers",
    email: "sviggersc@umn.edu",
    gender: "Female",
    country: "China",
    department: "Business Development",
    salary: 195000,
},
{
    id: 14,
    first_name: "Natasha",
    last_name: "Benterman",
    email: "nbentermand@google.nl",
    gender: "Female",
    country: "Nauru",
    department: "Engineering",
    salary: 255000,
},
{
    id: 15,
    first_name: "Florry",
    last_name: "Over",
    email: "fovere@netlog.com",
    gender: "Female",
    country: "China",
    department: "Legal",
    salary: 135000,
},
{
    id: 16,
    first_name: "Filia",
    last_name: "Ormrod",
    email: "formrodf@kickstarter.com",
    gender: "Polygender",
    country: "Tanzania",
    department: "Marketing",
    salary: 150000,
},
{
    id: 17,
    first_name: "Amos",
    last_name: "Swafford",
    email: "aswaffordg@addthis.com",
    gender: "Male",
    country: "Mongolia",
    department: "Business Development",
    salary: 290000,
},
{
    id: 18,
    first_name: "Wood",
    last_name: "Foss",
    email: "wfossh@npr.org",
    gender: "Male",
    country: "Moldova",
    department: "Training",
    salary: 40000,
},
{
    id: 19,
    first_name: "Corbin",
    last_name: "Phipps",
    email: "cphippsi@aboutads.info",
    gender: "Male",
    country: "South Africa",
    department: "Sales",
    salary: 105000,
},
{
    id: 20,
    first_name: "Adolpho",
    last_name: "Bevir",
    email: "abevirj@sciencedaily.com",
    gender: "Male",
    country: "Afghanistan",
    department: "Training",
    salary: 225000,
},
{
    id: 21,
    first_name: "Noble",
    last_name: "Syseland",
    email: "nsyselandk@google.com.hk",
    gender: "Male",
    country: "Argentina",
    department: "Training",
    salary: 30000,
},
{
    id: 22,
    first_name: "Adelaida",
    last_name: "Goodfellowe",
    email: "agoodfellowel@ucsd.edu",
    gender: "Female",
    country: "Indonesia",
    department: "Research and Development",
    salary: 75000,
},
{
    id: 23,
    first_name: "Sella",
    last_name: "Danne",
    email: "sdannem@amazon.co.uk",
    gender: "Female",
    country: "Mongolia",
    department: "Sales",
    salary: 185000,
},
{
    id: 24,
    first_name: "Randi",
    last_name: "Cranny",
    email: "rcrannyn@oaic.gov.au",
    gender: "Male",
    country: "Japan",
    department: "Engineering",
    salary: 40000,
},
{
    id: 25,
    first_name: "Angelita",
    last_name: "Kornyshev",
    email: "akornyshevo@dropbox.com",
    gender: "Female",
    country: "Armenia",
    department: "Marketing",
    salary: 185000,
},
{
    id: 26,
    first_name: "Matilde",
    last_name: "Haggarty",
    email: "mhaggartyp@independent.co.uk",
    gender: "Female",
    country: "Russia",
    department: "Sales",
    salary: 60000,
},
{
    id: 27,
    first_name: "Reggie",
    last_name: "Hocking",
    email: "rhockingq@usa.gov",
    gender: "Genderqueer",
    country: "Indonesia",
    department: "Research and Development",
    salary: 220000,
},
{
    id: 28,
    first_name: "Yardley",
    last_name: "Woodburne",
    email: "ywoodburner@illinois.edu",
    gender: "Male",
    country: "Aland Islands",
    department: "Support",
    salary: 130000,
},
{
    id: 29,
    first_name: "Tiffie",
    last_name: "Espie",
    email: "tespies@google.pl",
    gender: "Female",
    country: "Poland",
    department: "Product Management",
    salary: 280000,
},
{
    id: 30,
    first_name: "Doretta",
    last_name: "Fincher",
    email: "dfinchert@umn.edu",
    gender: "Female",
    country: "China",
    department: "Support",
    salary: 235000,
},
{
    id: 31,
    first_name: "Carola",
    last_name: "Morteo",
    email: "cmorteou@mozilla.org",
    gender: "Female",
    country: "Argentina",
    department: "Research and Development",
    salary: 95000,
},
{
    id: 32,
    first_name: "Cole",
    last_name: "Mugleston",
    email: "cmuglestonv@java.com",
    gender: "Male",
    country: "Ghana",
    department: "Services",
    salary: 45000,
},
{
    id: 33,
    first_name: "Beverlie",
    last_name: "Deakin",
    email: "bdeakinw@hc360.com",
    gender: "Female",
    country: "Kosovo",
    department: "Engineering",
    salary: 240000,
},
{
    id: 34,
    first_name: "Hasty",
    last_name: "Bubear",
    email: "hbubearx@dagondesign.com",
    gender: "Male",
    country: "Indonesia",
    department: "Product Management",
    salary: 40000,
},
{
    id: 35,
    first_name: "Rolf",
    last_name: "Gaenor",
    email: "rgaenory@icio.us",
    gender: "Male",
    country: "Vietnam",
    department: "Business Development",
    salary: 255000,
},
{
    id: 36,
    first_name: "Jackqueline",
    last_name: "Harflete",
    email: "jharfletez@dailymail.co.uk",
    gender: "Female",
    country: "Sweden",
    department: "Services",
    salary: 290000,
},
{
    id: 37,
    first_name: "Tracy",
    last_name: "Vibert",
    email: "tvibert10@paginegialle.it",
    gender: "Female",
    country: "Sweden",
    department: "Marketing",
    salary: 235000,
},
{
    id: 38,
    first_name: "Aili",
    last_name: "Tinston",
    email: "atinston11@smugmug.com",
    gender: "Female",
    country: "Russia",
    department: "Legal",
    salary: 260000,
},
{
    id: 39,
    first_name: "Saraann",
    last_name: "Ridgway",
    email: "sridgway12@loc.gov",
    gender: "Genderqueer",
    country: "Russia",
    department: "Marketing",
    salary: 200000,
},
{
    id: 40,
    first_name: "Shirl",
    last_name: "Thecham",
    email: "sthecham13@nationalgeographic.com",
    gender: "Female",
    country: "China",
    department: "Services",
    salary: 155000,
},
{
    id: 41,
    first_name: "Rosalyn",
    last_name: "Earley",
    email: "rearley14@usatoday.com",
    gender: "Female",
    country: "Netherlands",
    department: "Research and Development",
    salary: 120000,
},
{
    id: 42,
    first_name: "Megen",
    last_name: "Garbott",
    email: "mgarbott15@newyorker.com",
    gender: "Female",
    country: "Japan",
    department: "Product Management",
    salary: 90000,
},
{
    id: 43,
    first_name: "Chandal",
    last_name: "Darque",
    email: "cdarque16@weibo.com",
    gender: "Female",
    country: "Indonesia",
    department: "Support",
    salary: 35000,
},
{
    id: 44,
    first_name: "Etienne",
    last_name: "Hocking",
    email: "ehocking17@apple.com",
    gender: "Male",
    country: "Tanzania",
    department: "Services",
    salary: 145000,
},
{
    id: 45,
    first_name: "Sue",
    last_name: "Chirm",
    email: "schirm18@washington.edu",
    gender: "Female",
    country: "Brazil",
    department: "Product Management",
    salary: 255000,
},
{
    id: 46,
    first_name: "Thekla",
    last_name: "Killich",
    email: "tkillich19@sciencedaily.com",
    gender: "Female",
    country: "South Africa",
    department: "Human Resources",
    salary: 135000,
},
{
    id: 47,
    first_name: "Tad",
    last_name: "Blofield",
    email: "tblofield1a@mysql.com",
    gender: "Male",
    country: "Philippines",
    department: "Accounting",
    salary: 135000,
},
{
    id: 48,
    first_name: "Dulcie",
    last_name: "Lammenga",
    email: "dlammenga1b@alexa.com",
    gender: "Female",
    country: "China",
    department: "Legal",
    salary: 125000,
},
{
    id: 49,
    first_name: "Xenos",
    last_name: "Eicheler",
    email: "xeicheler1c@mapquest.com",
    gender: "Male",
    country: "Japan",
    department: "Engineering",
    salary: 280000,
},
{
    id: 50,
    first_name: "Vyky",
    last_name: "Donaldson",
    email: "vdonaldson1d@yandex.ru",
    gender: "Female",
    country: "United States",
    department: "Services",
    salary: 190000,
},
{
    id: 51,
    first_name: "Fianna",
    last_name: "Bocken",
    email: "fbocken1e@pinterest.com",
    gender: "Female",
    country: "Russia",
    department: "Sales",
    salary: 160000,
},
{
    id: 52,
    first_name: "Lorene",
    last_name: "Mannin",
    email: "lmannin1f@tmall.com",
    gender: "Genderfluid",
    country: "Mali",
    department: "Services",
    salary: 30000,
},
{
    id: 53,
    first_name: "Leela",
    last_name: "Blandamere",
    email: "lblandamere1g@tripod.com",
    gender: "Female",
    country: "China",
    department: "Engineering",
    salary: 55000,
},
{
    id: 54,
    first_name: "Marci",
    last_name: "Osgordby",
    email: "mosgordby1h@tinyurl.com",
    gender: "Female",
    country: "Peru",
    department: "Research and Development",
    salary: 85000,
},
{
    id: 55,
    first_name: "Ansel",
    last_name: "Lagen",
    email: "alagen1i@google.ca",
    gender: "Male",
    country: "Russia",
    department: "Services",
    salary: 80000,
},
{
    id: 56,
    first_name: "Chrissy",
    last_name: "Brattan",
    email: "cbrattan1j@wunderground.com",
    gender: "Male",
    country: "Peru",
    department: "Training",
    salary: 175000,
},
{
    id: 57,
    first_name: "Valentia",
    last_name: "Downer",
    email: "vdowner1k@nifty.com",
    gender: "Female",
    country: "Japan",
    department: "Support",
    salary: 145000,
},
{
    id: 58,
    first_name: "Gris",
    last_name: "Robken",
    email: "grobken1l@goo.gl",
    gender: "Male",
    country: "China",
    department: "Services",
    salary: 240000,
},
{
    id: 59,
    first_name: "Murry",
    last_name: "Gibbens",
    email: "mgibbens1m@vistaprint.com",
    gender: "Male",
    country: "Argentina",
    department: "Product Management",
    salary: 220000,
},
{
    id: 60,
    first_name: "Barnebas",
    last_name: "Yantsev",
    email: "byantsev1n@homestead.com",
    gender: "Male",
    country: "Tunisia",
    department: "Accounting",
    salary: 190000,
},
{
    id: 61,
    first_name: "Alia",
    last_name: "Meth",
    email: "ameth1o@umich.edu",
    gender: "Female",
    country: "Indonesia",
    department: "Training",
    salary: 250000,
},
{
    id: 62,
    first_name: "Joanie",
    last_name: "Mills",
    email: "jmills1p@businessweek.com",
    gender: "Female",
    country: "France",
    department: "Legal",
    salary: 130000,
},
{
    id: 63,
    first_name: "Mikey",
    last_name: "Helm",
    email: "mhelm1q@ning.com",
    gender: "Male",
    country: "Thailand",
    department: "Training",
    salary: 110000,
},
{
    id: 64,
    first_name: "Darrin",
    last_name: "Alwen",
    email: "dalwen1r@freewebs.com",
    gender: "Genderfluid",
    country: "Peru",
    department: "Human Resources",
    salary: 155000,
},
{
    id: 65,
    first_name: "Stella",
    last_name: "Baudts",
    email: "sbaudts1s@xinhuanet.com",
    gender: "Female",
    country: "Indonesia",
    department: "Human Resources",
    salary: 40000,
},
{
    id: 66,
    first_name: "Coleman",
    last_name: "Sherlaw",
    email: "csherlaw1t@nba.com",
    gender: "Male",
    country: "Nigeria",
    department: "Engineering",
    salary: 280000,
},
{
    id: 67,
    first_name: "Raynor",
    last_name: "Paylor",
    email: "rpaylor1u@freewebs.com",
    gender: "Male",
    country: "Thailand",
    department: "Sales",
    salary: 240000,
},
{
    id: 68,
    first_name: "Raf",
    last_name: "Relton",
    email: "rrelton1v@dmoz.org",
    gender: "Bigender",
    country: "Ukraine",
    department: "Services",
    salary: 190000,
},
{
    id: 69,
    first_name: "Luciano",
    last_name: "Lanham",
    email: "llanham1w@sphinn.com",
    gender: "Agender",
    country: "Serbia",
    department: "Legal",
    salary: 90000,
},
{
    id: 70,
    first_name: "Olin",
    last_name: "Stott",
    email: "ostott1x@a8.net",
    gender: "Male",
    country: "Argentina",
    department: "Accounting",
    salary: 115000,
},
{
    id: 71,
    first_name: "Maddie",
    last_name: "Houlison",
    email: "mhoulison1y@walmart.com",
    gender: "Male",
    country: "Peru",
    department: "Training",
    salary: 75000,
},
{
    id: 72,
    first_name: "Fifine",
    last_name: "Brake",
    email: "fbrake1z@wp.com",
    gender: "Female",
    country: "Tunisia",
    department: "Engineering",
    salary: 210000,
},
{
    id: 73,
    first_name: "Mordecai",
    last_name: "Hewertson",
    email: "mhewertson20@usa.gov",
    gender: "Male",
    country: "Italy",
    department: "Research and Development",
    salary: 290000,
},
{
    id: 74,
    first_name: "Clywd",
    last_name: "Silburn",
    email: "csilburn21@about.me",
    gender: "Male",
    country: "Russia",
    department: "Product Management",
    salary: 255000,
},
{
    id: 75,
    first_name: "Araldo",
    last_name: "Fulbrook",
    email: "afulbrook22@apache.org",
    gender: "Male",
    country: "China",
    department: "Product Management",
    salary: 30000,
},
{
    id: 76,
    first_name: "Melisenda",
    last_name: "Cramer",
    email: "mcramer23@yelp.com",
    gender: "Female",
    country: "Japan",
    department: "Legal",
    salary: 200000,
},
{
    id: 77,
    first_name: "Garrick",
    last_name: "Gomme",
    email: "ggomme24@amazon.de",
    gender: "Male",
    country: "Mongolia",
    department: "Support",
    salary: 115000,
},
{
    id: 78,
    first_name: "Ameline",
    last_name: "Gilmore",
    email: "agilmore25@ted.com",
    gender: "Female",
    country: "Indonesia",
    department: "Research and Development",
    salary: 275000,
},
{
    id: 79,
    first_name: "Olvan",
    last_name: "Checci",
    email: "ochecci26@wiley.com",
    gender: "Male",
    country: "Indonesia",
    department: "Engineering",
    salary: 230000,
},
{
    id: 80,
    first_name: "Andrea",
    last_name: "Campling",
    email: "acampling27@gizmodo.com",
    gender: "Polygender",
    country: "China",
    department: "Accounting",
    salary: 155000,
},
{
    id: 81,
    first_name: "Mildrid",
    last_name: "Boutellier",
    email: "mboutellier28@ed.gov",
    gender: "Female",
    country: "Japan",
    department: "Research and Development",
    salary: 70000,
},
{
    id: 82,
    first_name: "Kayley",
    last_name: "Penchen",
    email: "kpenchen29@earthlink.net",
    gender: "Female",
    country: "Luxembourg",
    department: "Business Development",
    salary: 110000,
},
{
    id: 83,
    first_name: "Jermaine",
    last_name: "Finden",
    email: "jfinden2a@icq.com",
    gender: "Female",
    country: "China",
    department: "Accounting",
    salary: 180000,
},
{
    id: 84,
    first_name: "Damara",
    last_name: "Huckerby",
    email: "dhuckerby2b@paypal.com",
    gender: "Female",
    country: "China",
    department: "Product Management",
    salary: 155000,
},
{
    id: 85,
    first_name: "Terry",
    last_name: "Thorley",
    email: "tthorley2c@purevolume.com",
    gender: "Female",
    country: "Canada",
    department: "Accounting",
    salary: 265000,
},
{
    id: 86,
    first_name: "Alphonse",
    last_name: "Diss",
    email: "adiss2d@facebook.com",
    gender: "Male",
    country: "South Korea",
    department: "Support",
    salary: 85000,
},
{
    id: 87,
    first_name: "Kiley",
    last_name: "Dumigan",
    email: "kdumigan2e@dyndns.org",
    gender: "Female",
    country: "United States",
    department: "Product Management",
    salary: 180000,
},
{
    id: 88,
    first_name: "Giselle",
    last_name: "Lammertz",
    email: "glammertz2f@nyu.edu",
    gender: "Female",
    country: "Myanmar",
    department: "Support",
    salary: 185000,
},
{
    id: 89,
    first_name: "Poppy",
    last_name: "Vigneron",
    email: "pvigneron2g@google.com.br",
    gender: "Polygender",
    country: "China",
    department: "Marketing",
    salary: 120000,
},
{
    id: 90,
    first_name: "Odell",
    last_name: "Ormrod",
    email: "oormrod2h@hexun.com",
    gender: "Male",
    country: "Slovenia",
    department: "Business Development",
    salary: 130000,
},
{
    id: 91,
    first_name: "Ruthe",
    last_name: "Zylbermann",
    email: "rzylbermann2i@gnu.org",
    gender: "Female",
    country: "China",
    department: "Support",
    salary: 70000,
},
{
    id: 92,
    first_name: "Liam",
    last_name: "Lehmann",
    email: "llehmann2j@hp.com",
    gender: "Male",
    country: "Peru",
    department: "Support",
    salary: 45000,
},
{
    id: 93,
    first_name: "Anstice",
    last_name: "Yele",
    email: "ayele2k@list-manage.com",
    gender: "Female",
    country: "Poland",
    department: "Human Resources",
    salary: 235000,
},
{
    id: 94,
    first_name: "Carol",
    last_name: "Bracken",
    email: "cbracken2l@cnn.com",
    gender: "Female",
    country: "China",
    department: "Human Resources",
    salary: 220000,
},
{
    id: 95,
    first_name: "Daphne",
    last_name: "Celle",
    email: "dcelle2m@ifeng.com",
    gender: "Female",
    country: "China",
    department: "Marketing",
    salary: 275000,
},
{
    id: 96,
    first_name: "Aviva",
    last_name: "Mattosoff",
    email: "amattosoff2n@twitpic.com",
    gender: "Female",
    country: "Iran",
    department: "Sales",
    salary: 150000,
},
{
    id: 97,
    first_name: "Zilvia",
    last_name: "Cordelle",
    email: "zcordelle2o@nba.com",
    gender: "Female",
    country: "Brazil",
    department: "Accounting",
    salary: 130000,
},
{
    id: 98,
    first_name: "Porter",
    last_name: "Nuzzetti",
    email: "pnuzzetti2p@illinois.edu",
    gender: "Male",
    country: "Brazil",
    department: "Research and Development",
    salary: 180000,
},
{
    id: 99,
    first_name: "Aline",
    last_name: "Moutray Read",
    email: "amoutrayread2q@nationalgeographic.com",
    gender: "Female",
    country: "Egypt",
    department: "Sales",
    salary: 55000,
},
{
    id: 100,
    first_name: "Dal",
    last_name: "Langsdon",
    email: "dlangsdon2r@wired.com",
    gender: "Male",
    country: "China",
    department: "Human Resources",
    salary: 205000,
},
];

// console.log(employees["email"]);

function getLowestSalary(salary){
    let lowest = employees[0]
    for(let i = 1; i < employees.length ; i++){
        if(employees[i]["salary"] < Number(lowest.salary)){
            return lowest = employees[i]
        }
    }
    return lowest
}


console.log(getLowestSalary(employees));
// console.log(getLowestSalary(30000));